import type { NextPage } from "next"
import Head from "next/head"
import styled from "styled-components"

const List: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>list page</h1>
      </Container>
    </div>
  )
}

const Container = styled.main`
  background: red;
`

export default List
