import type { NextPage } from "next"
import Head from "next/head"

const Map: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>map page</h1>
      </main>
    </div>
  )
}

export default Map
